### PR TITLE
ocsm: Fix wrong file extension and wrong extract command

### PR DESCRIPTION
**Pull request by rootjack404**
Details in https://github.com/helmiau/HelmiWrt-OS/issues/41#issuecomment-930801420

### CODE REVIEW

**Comment by malikshi** [comment]
@rootjack404 
i will try to test it

**Comment by rootjack404** [comment]
Seems like i make a mistake on the mv command, i included the $PREMEXT, so it might file to move. Sorry

**Comment by helmiau** [comment]
Ini @rootjack404 om Jaki Rahman yg di FB itu bukan ?

klo iya, biar nnti saya masukkan credits di web

**Comment by rootjack404** [comment]
> Ini @rootjack404 om Jaki Rahman yg di FB itu bukan ?
> 
> klo iya, biar nnti saya masukkan credits di web

Yap, tapi ini masih error setelah saya test di stb sih. Lagi dicoba dibenerin lagi

**Comment by rootjack404** [comment]
Screenshot_20210930_185332

It should work now

**Comment by helmiau** [comment]
issue #41 fixed?

**Pull request merged**
